console.log('AIVA Login Issue Solution');
console.log('========================');
console.log('');
console.log('The "Invalid email or password" error is occurring because the password hash stored in the database');
console.log('does not match the password you are entering.');
console.log('');
console.log('Solution:');
console.log('==========');
console.log('');
console.log('1. Create a new test user with known credentials:');
console.log('   - Go to the registration page in the web app');
console.log('   - Register with:');
console.log('     * Email: test@example.com');
console.log('     * Password: password123');
console.log('     * First Name: Test');
console.log('     * Last Name: User');
console.log('');
console.log('2. After registration, try to log in with those exact credentials');
console.log('');
console.log('3. If you still have issues, check the following:');
console.log('   - Make sure the server is running');
console.log('   - Verify database connection settings in your .env file');
console.log('   - Check that the email address matches exactly (case-sensitive)');
console.log('');
console.log('Alternative solution:');
console.log('====================');
console.log('If you have database access, you can manually update the user\'s password hash to:');
console.log('$2a$12$mv.FNFeffOlPPCrIWOX8aOQgS3LHLIrC44q/MV0dfMACEYxxJaWEW');
console.log('(This is the bcrypt hash for "password123")');
console.log('');
console.log('For admin user, use:');
console.log('Email: admin@example.com');
console.log('Password: admin123');